// lib/catalog.ts
// Full 40-category × 100-product deterministic catalog for Worldwide Shopio
// All data is fictional. No real brand assets are used.

export interface CatalogProduct {
  id: string
  sku: string
  name: string
  brand: string
  category: string
  subcategory: string
  price: number
  originalPrice?: number
  discount?: number
  images: string[]
  description: string
  rating: number
  reviews: number
  inStock: boolean
  stock: number
  badge?: string
  tags: string[]
  specs: Record<string, string>
  colors?: string[]
  sizes?: string[]
}

// ── Placeholder image pool (Unsplash/Picsum style via category seeds) ─────────
// We use deterministic picsum.photos URLs keyed by product id seed
function img(seed: number, w = 600, h = 600) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`
}

// ── Helpers ──────────────────────────────────────────────────────────────────
function lerp(a: number, b: number, t: number) {
  return Math.round(a + (b - a) * t)
}
function pick<T>(arr: T[], seed: number): T {
  return arr[seed % arr.length]
}
function rating(seed: number): number {
  const base = [4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0]
  return pick(base, seed)
}
function reviews(seed: number): number {
  const bases = [12, 24, 38, 55, 71, 88, 103, 146, 204, 312, 450, 682, 891, 1024, 1500]
  return pick(bases, seed * 3)
}
function badge(seed: number, price: number, originalPrice?: number): string | undefined {
  if (originalPrice && originalPrice > price) return 'Sale'
  const b = seed % 10
  if (b === 0) return 'New'
  if (b === 1) return 'Hot'
  if (b === 2) return 'Trending'
  if (b === 3) return 'Limited'
  return undefined
}
function inStock(seed: number): boolean {
  return seed % 12 !== 0
}
function stock(seed: number): number {
  if (!inStock(seed)) return 0
  const opts = [3, 5, 8, 12, 20, 35, 50, 75, 100, 150, 200]
  return pick(opts, seed * 7)
}
function discount(seed: number): number | undefined {
  const discounts = [undefined, undefined, undefined, 5, 10, 15, 20, 25, 30, 40, 50]
  return pick(discounts, seed * 2)
}

// ── Category definitions ──────────────────────────────────────────────────────
interface CatDef {
  name: string
  subcategory: string
  priceRange: [number, number]
  brands: string[]
  nameParts: [string[], string[]] // adjectives[], nouns[]
  colors?: string[]
  sizes?: string[]
  tags: string[]
  specKeys: string[]
  specValues: Record<string, string[]>
}

const CATEGORIES: CatDef[] = [
  // 0 — Men's Fashion
  {
    name: "Men's Fashion",
    subcategory: 'Clothing',
    priceRange: [25, 350],
    brands: [
      'Arkon',
      'Vantex',
      'Meridian',
      'Greystone',
      'Halcyon',
      'Foxford',
      'Umbrel',
      'Calderon',
    ],
    nameParts: [
      [
        'Slim',
        'Classic',
        'Modern',
        'Essential',
        'Premium',
        'Urban',
        'Heritage',
        'Relaxed',
        'Tailored',
        'Athletic',
      ],
      [
        'Blazer',
        'Shirt',
        'Polo',
        'Henley',
        'Chino',
        'Trouser',
        'Jogger',
        'Hoodie',
        'Cardigan',
        'Vest',
      ],
    ],
    colors: ['Black', 'Navy', 'White', 'Grey', 'Charcoal', 'Olive', 'Beige', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'],
    tags: ['men', 'fashion', 'clothing', 'apparel', 'casual', 'formal'],
    specKeys: ['Material', 'Fit', 'Collar', 'Care'],
    specValues: {
      Material: [
        '100% Cotton',
        '95% Cotton 5% Elastane',
        'Polyester Blend',
        'Linen Blend',
        'Wool Blend',
        'Denim',
      ],
      Fit: ['Slim Fit', 'Regular Fit', 'Relaxed Fit', 'Athletic Fit', 'Tapered Fit'],
      Collar: ['Round Neck', 'V-Neck', 'Collar', 'Stand Collar', 'Henley', 'Polo'],
      Care: ['Machine Wash Cold', 'Hand Wash Only', 'Dry Clean Only', 'Machine Wash Warm'],
    },
  },
  // 1 — Women's Fashion
  {
    name: "Women's Fashion",
    subcategory: 'Clothing',
    priceRange: [25, 450],
    brands: ['Elara', 'Vivette', 'Luminae', 'Soirée', 'Perlux', 'Verselle', 'Aurae', 'Claret'],
    nameParts: [
      ['Floral', 'Wrap', 'A-Line', 'Silk', 'Linen', 'Knit', 'Velvet', 'Chiffon', 'Satin', 'Midi'],
      [
        'Dress',
        'Blouse',
        'Skirt',
        'Jumpsuit',
        'Cardigan',
        'Top',
        'Blazer',
        'Maxi',
        'Bodysuit',
        'Tunic',
      ],
    ],
    colors: ['Black', 'White', 'Blush', 'Navy', 'Emerald', 'Camel', 'Coral', 'Lavender'],
    sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL'],
    tags: ['women', 'fashion', 'clothing', 'apparel', 'dress', 'casual'],
    specKeys: ['Material', 'Fit', 'Length', 'Care'],
    specValues: {
      Material: ['100% Silk', '95% Polyester', 'Viscose Blend', 'Cotton-Linen', 'Satin', 'Chiffon'],
      Fit: ['Slim Fit', 'Regular Fit', 'Relaxed Fit', 'Bodycon', 'A-Line'],
      Length: ['Mini', 'Midi', 'Maxi', 'Knee-Length', 'Above Knee'],
      Care: ['Hand Wash Only', 'Machine Wash Delicate', 'Dry Clean Only'],
    },
  },
  // 2 — Korean Fashion
  {
    name: 'Korean Fashion',
    subcategory: 'K-Style',
    priceRange: [20, 280],
    brands: ['Seouli', 'Hanbek', 'Dongwon Style', 'Mirae', 'Cheonha', 'Ssaem', 'Nuri K', 'Yeonhwa'],
    nameParts: [
      [
        'Minimal',
        'Street',
        'Pastel',
        'Oversized',
        'Cropped',
        'Wide-leg',
        'Y2K',
        'Harajuku',
        'Aesthetic',
        'Soft',
      ],
      ['Hoodie', 'Tee', 'Cardigan', 'Jogger', 'Blazer', 'Dress', 'Skirt', 'Jacket', 'Pants', 'Set'],
    ],
    colors: ['Beige', 'Cream', 'Pastel Blue', 'Pink', 'Mint', 'Light Grey', 'Lavender', 'White'],
    sizes: ['Free', 'S', 'M', 'L', 'XL'],
    tags: ['korean', 'kfashion', 'streetwear', 'ulzzang', 'minimal', 'aesthetic'],
    specKeys: ['Material', 'Style', 'Fit', 'Origin'],
    specValues: {
      Material: ['Cotton Blend', 'Knit', 'Fleece', 'Woven Fabric', 'Jersey'],
      Style: ['Casual', 'Street', 'Minimal', 'Preppy', 'Y2K'],
      Fit: ['Oversized', 'Slim', 'Regular', 'Cropped'],
      Origin: ['South Korea', 'Designed in Seoul'],
    },
  },
  // 3 — Kids Fashion
  {
    name: 'Kids Fashion',
    subcategory: 'Children',
    priceRange: [12, 120],
    brands: [
      'Tinytops',
      'Kidcore',
      'Sproutly',
      'BabyBlu',
      'Munchkin Co.',
      'Playwell',
      'Littlefit',
      'Dreamy Kids',
    ],
    nameParts: [
      [
        'Cute',
        'Fun',
        'Comfy',
        'Bright',
        'Soft',
        'Printed',
        'Adventure',
        'Rainbow',
        'Cozy',
        'Playful',
      ],
      [
        'T-Shirt',
        'Shorts',
        'Dress',
        'Dungarees',
        'Hoodie',
        'Pajama',
        'Set',
        'Jacket',
        'Sweater',
        'Leggings',
      ],
    ],
    colors: ['Red', 'Blue', 'Yellow', 'Green', 'Pink', 'Purple', 'Orange', 'Multicolor'],
    sizes: ['2Y', '3Y', '4Y', '5Y', '6Y', '7Y', '8Y', '9Y', '10Y', '12Y'],
    tags: ['kids', 'children', 'baby', 'toddler', 'school', 'play'],
    specKeys: ['Material', 'Age Group', 'Gender', 'Care'],
    specValues: {
      Material: ['100% Cotton', 'Organic Cotton', 'Fleece', 'Polyester Blend'],
      'Age Group': ['2-4 Years', '4-6 Years', '6-8 Years', '8-12 Years'],
      Gender: ['Boys', 'Girls', 'Unisex'],
      Care: ['Machine Wash 30°C', 'Machine Wash 40°C', 'Hand Wash'],
    },
  },
  // 4 — Shoes
  {
    name: 'Shoes',
    subcategory: 'Footwear',
    priceRange: [35, 480],
    brands: [
      'Strideaux',
      'Velmont',
      'Cordova',
      'Lestrade',
      'Orthofit',
      'Zenith Step',
      'Footmark',
      'Cadence',
    ],
    nameParts: [
      [
        'Leather',
        'Classic',
        'Oxford',
        'Derby',
        'Chelsea',
        'Loafer',
        'Monk',
        'Brogue',
        'Wingtip',
        'Slip-On',
      ],
      [
        'Shoe',
        'Boot',
        'Pump',
        'Heel',
        'Mule',
        'Flat',
        'Wedge',
        'Platform',
        'Ankle Boot',
        'Block Heel',
      ],
    ],
    colors: ['Black', 'Brown', 'Tan', 'Burgundy', 'Navy', 'White', 'Nude'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
    tags: ['shoes', 'footwear', 'leather', 'formal', 'casual', 'boots'],
    specKeys: ['Upper Material', 'Sole', 'Heel Height', 'Closure'],
    specValues: {
      'Upper Material': ['Genuine Leather', 'Suede', 'Patent Leather', 'Synthetic'],
      Sole: ['Rubber', 'Leather', 'EVA', 'TPU'],
      'Heel Height': ['Flat', '1 cm', '2 cm', '4 cm', '6 cm', '8 cm'],
      Closure: ['Lace-Up', 'Slip-On', 'Zip', 'Buckle', 'Velcro'],
    },
  },
  // 5 — Sneakers
  {
    name: 'Sneakers',
    subcategory: 'Footwear',
    priceRange: [45, 320],
    brands: [
      'RunCore',
      'CloudStep',
      'AeroPace',
      'Nexus Sport',
      'Hyperion',
      'FlexRun',
      'Kinetic',
      'ZeroG',
    ],
    nameParts: [
      ['Air', 'Cloud', 'Boost', 'Ultra', 'Pro', 'Flex', 'Neo', 'Hyper', 'Swift', 'Core'],
      [
        'Runner',
        'Trainer',
        'Racer',
        'Walker',
        'Jumper',
        'Rider',
        'Strider',
        'Pacer',
        'Sprint',
        'Dash',
      ],
    ],
    colors: ['White', 'Black', 'Grey', 'Red', 'Blue', 'Green', 'Volt', 'Coral'],
    sizes: ['UK 4', 'UK 5', 'UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11', 'UK 12'],
    tags: ['sneakers', 'trainers', 'running', 'sport', 'athleisure', 'casual'],
    specKeys: ['Upper', 'Midsole', 'Outsole', 'Weight', 'Drop'],
    specValues: {
      Upper: ['Mesh', 'Knit', 'Leather', 'Synthetic Mesh', 'Engineered Knit'],
      Midsole: ['EVA Foam', 'React Foam', 'Boost Foam', 'Air Unit', 'Gel Cushion'],
      Outsole: ['Rubber', 'Carbon Rubber', 'Continental Rubber', 'Blown Rubber'],
      Weight: ['220g', '245g', '268g', '290g', '310g'],
      Drop: ['0mm', '4mm', '8mm', '10mm', '12mm'],
    },
  },
  // 6 — Sandals
  {
    name: 'Sandals',
    subcategory: 'Footwear',
    priceRange: [18, 220],
    brands: [
      'Breezefoot',
      'Solaris',
      'Corfú',
      'Sandalora',
      'Barefoot Co.',
      'Tropica',
      'Shoreline',
      'Sundrift',
    ],
    nameParts: [
      [
        'Beach',
        'Comfort',
        'Strap',
        'Slide',
        'Toe-Post',
        'Platform',
        'Block',
        'Wedge',
        'Ankle',
        'Sporty',
      ],
      [
        'Sandal',
        'Flip-Flop',
        'Mule',
        'Slider',
        'Thong',
        'Huarache',
        'Gladiator',
        'Espadrille',
        'Flat',
        'Wedge',
      ],
    ],
    colors: ['Tan', 'Black', 'White', 'Brown', 'Gold', 'Silver', 'Coral', 'Nude'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43'],
    tags: ['sandals', 'summer', 'beach', 'casual', 'footwear', 'open-toe'],
    specKeys: ['Strap Material', 'Sole', 'Heel Type', 'Closure'],
    specValues: {
      'Strap Material': ['Leather', 'Synthetic', 'Fabric', 'Jute', 'Rubber'],
      Sole: ['EVA', 'Rubber', 'Cork', 'Wood', 'Foam'],
      'Heel Type': ['Flat', 'Wedge', 'Block', 'Kitten Heel', 'Platform'],
      Closure: ['Buckle', 'Velcro', 'Slip-On', 'Tie', 'Elastic'],
    },
  },
  // 7 — Slippers
  {
    name: 'Slippers',
    subcategory: 'Footwear',
    priceRange: [12, 95],
    brands: [
      'HomeStep',
      'CloudWalk',
      'CozyCraft',
      'Slumberwear',
      'Plushfoot',
      'WarmTread',
      'Softsole',
      'Fluffies',
    ],
    nameParts: [
      [
        'Memory Foam',
        'Plush',
        'Knit',
        'Anti-Slip',
        'Fluffy',
        'Thermal',
        'Open-Toe',
        'Closed-Toe',
        'Indoor',
        'Cozy',
      ],
      [
        'Slipper',
        'Mule',
        'Bootie',
        'Slide',
        'Clog',
        'Scuff',
        'Moccasin',
        'Ballerina',
        'Sherpa',
        'Loafer',
      ],
    ],
    colors: ['Grey', 'Black', 'Pink', 'Navy', 'Beige', 'Brown', 'Cream'],
    sizes: ['S/M', 'M/L', 'L/XL', 'UK 3-4', 'UK 5-6', 'UK 7-8', 'UK 9-10'],
    tags: ['slippers', 'indoor', 'cozy', 'home', 'warm', 'comfort'],
    specKeys: ['Lining', 'Sole', 'Closure', 'Insole'],
    specValues: {
      Lining: ['Fleece', 'Sherpa', 'Cotton', 'Memory Foam', 'Faux Fur'],
      Sole: ['Rubber', 'Anti-Slip TPR', 'EVA', 'Hard Sole'],
      Closure: ['Slip-On', 'Velcro', 'Elastic', 'Closed Back'],
      Insole: ['Memory Foam', 'EVA', 'Cushion Foam', 'Arch Support'],
    },
  },
  // 8 — Luxury Watches
  {
    name: 'Luxury Watches',
    subcategory: 'Timepieces',
    priceRange: [350, 8500],
    brands: [
      'Chronelle',
      'Auremis',
      'Valmont Horlogerie',
      'Luxtime',
      'Grandeur Watch Co.',
      'Elvior',
      'Celestique',
      'Rolex-Esque',
    ],
    nameParts: [
      [
        'Chronograph',
        'Tourbillon',
        'Perpetual',
        'Grand',
        'Royal',
        'Prestige',
        'Signature',
        'Heritage',
        'Classic',
        'Automatic',
      ],
      [
        'Timepiece',
        'Watch',
        'Collection',
        'Edition',
        'Series',
        'Complication',
        'Calendar',
        'Moon Phase',
        'Diver',
        'Pilot',
      ],
    ],
    colors: ['Silver/Black', 'Gold/Black', 'Rose Gold/White', 'Silver/Blue', 'Black/Gold'],
    sizes: ['38mm', '40mm', '42mm', '44mm', '46mm'],
    tags: ['watch', 'luxury', 'automatic', 'swiss', 'timepiece', 'collector'],
    specKeys: [
      'Movement',
      'Case Material',
      'Crystal',
      'Water Resistance',
      'Case Diameter',
      'Strap',
    ],
    specValues: {
      Movement: ['Swiss Automatic', 'Quartz', 'Mechanical', 'Solar', 'Kinetic'],
      'Case Material': [
        '316L Stainless Steel',
        '18K Gold Plated',
        'Rose Gold PVD',
        'Titanium',
        'Ceramic',
      ],
      Crystal: ['Sapphire Crystal', 'Mineral Glass', 'Hesalite Crystal'],
      'Water Resistance': ['30m', '50m', '100m', '200m', '300m'],
      'Case Diameter': ['38mm', '40mm', '42mm', '44mm', '46mm'],
      Strap: ['Leather Strap', 'Stainless Steel Bracelet', 'Rubber Strap', 'Fabric NATO Strap'],
    },
  },
  // 9 — Smart Watches
  {
    name: 'Smart Watches',
    subcategory: 'Wearables',
    priceRange: [49, 650],
    brands: [
      'NexBand',
      'Quantix',
      'PulseIQ',
      'FitCore',
      'VitaWatch',
      'HealthEdge',
      'SmartLux',
      'ActivePro',
    ],
    nameParts: [
      ['Active', 'Pulse', 'Fit', 'Pro', 'Ultra', 'Core', 'Zen', 'Apex', 'Elite', 'Max'],
      [
        'Watch',
        'Band',
        'Tracker',
        'Series',
        'Edition',
        'Connect',
        'Health',
        'Sport',
        'Lite',
        'Gen',
      ],
    ],
    colors: ['Black', 'Silver', 'Gold', 'Rose Gold', 'Midnight', 'Starlight'],
    sizes: ['41mm', '44mm', '45mm', '49mm'],
    tags: ['smartwatch', 'wearable', 'fitness', 'health', 'GPS', 'heart rate'],
    specKeys: [
      'Display',
      'Battery Life',
      'OS Compatibility',
      'Water Rating',
      'Sensors',
      'Connectivity',
    ],
    specValues: {
      Display: ['1.4" AMOLED', '1.6" AMOLED', '1.8" LCD', '1.9" AMOLED', '1.3" OLED'],
      'Battery Life': ['7 days', '10 days', '14 days', '18 days', '2 days'],
      'OS Compatibility': ['iOS & Android', 'Android only', 'iOS & Android (full)', 'Universal'],
      'Water Rating': ['IP67', 'IP68', '5ATM', '10ATM'],
      Sensors: [
        'Heart Rate, SpO2, GPS',
        'Heart Rate, SpO2, GPS, ECG',
        'Heart Rate, GPS',
        'HR, Stress, SpO2, GPS, Temp',
      ],
      Connectivity: ['Bluetooth 5.0', 'Bluetooth 5.2 + WiFi', 'Bluetooth 5.3 + LTE'],
    },
  },
  // 10 — Sunglasses
  {
    name: 'Sunglasses',
    subcategory: 'Eyewear',
    priceRange: [22, 420],
    brands: [
      'Visorex',
      'Luminae Optics',
      'Shadelux',
      'Clarion',
      'Optika',
      'SunShield',
      'Ray-Alike',
      'Glacé Eyewear',
    ],
    nameParts: [
      [
        'Aviator',
        'Wayfarer',
        'Cat-Eye',
        'Round',
        'Square',
        'Oversized',
        'Sporty',
        'Shield',
        'Browline',
        'Geometric',
      ],
      [
        'Sunglasses',
        'Shades',
        'Frames',
        'Collection',
        'Lenses',
        'Edition',
        'Classic',
        'Style',
        'Series',
        'UV400',
      ],
    ],
    colors: [
      'Black/Black',
      'Gold/Brown',
      'Silver/Grey',
      'Tortoise/Green',
      'Rose/Pink',
      'Clear/Blue',
    ],
    tags: ['sunglasses', 'eyewear', 'UV protection', 'polarized', 'fashion', 'summer'],
    specKeys: ['Frame Material', 'Lens Type', 'UV Protection', 'Lens Width', 'Bridge Width'],
    specValues: {
      'Frame Material': ['Acetate', 'Metal', 'TR90', 'Titanium', 'Injected Plastic'],
      'Lens Type': ['Polarized', 'Mirrored', 'Gradient', 'Photochromic', 'Standard'],
      'UV Protection': ['UV400', '100% UV Protection', 'UVA & UVB 400nm'],
      'Lens Width': ['52mm', '54mm', '56mm', '58mm', '60mm'],
      'Bridge Width': ['14mm', '16mm', '18mm', '20mm'],
    },
  },
  // 11 — Wallets
  {
    name: 'Wallets',
    subcategory: 'Small Leather Goods',
    priceRange: [18, 280],
    brands: [
      'Cordovan',
      'Slimfold',
      'Cardhive',
      'Leathercraft',
      'Noctua',
      'Meridian Leather',
      'Walletco',
      'Slimman',
    ],
    nameParts: [
      [
        'Slim',
        'Bifold',
        'Trifold',
        'Minimalist',
        'RFID',
        'Zip-Around',
        'Card',
        'Money Clip',
        'Long',
        'Travel',
      ],
      [
        'Wallet',
        'Card Holder',
        'Billfold',
        'Purse',
        'Cardholder',
        'Case',
        'Clip',
        'Organizer',
        'Pouch',
        'Fold',
      ],
    ],
    colors: ['Black', 'Brown', 'Tan', 'Navy', 'Burgundy', 'Grey', 'Cognac'],
    tags: ['wallet', 'leather', 'RFID', 'card holder', 'minimalist', 'accessories'],
    specKeys: ['Material', 'Card Slots', 'Note Compartments', 'Closure', 'RFID Blocking'],
    specValues: {
      Material: [
        'Full-Grain Leather',
        'Top-Grain Leather',
        'Genuine Leather',
        'Canvas',
        'Vegan Leather',
      ],
      'Card Slots': ['4', '6', '8', '10', '12'],
      'Note Compartments': ['1', '2'],
      Closure: ['Open-Top', 'Zip', 'Snap Button', 'Magnetic'],
      'RFID Blocking': ['Yes', 'No'],
    },
  },
  // 12 — Bags & Backpacks
  {
    name: 'Bags & Backpacks',
    subcategory: 'Bags',
    priceRange: [28, 680],
    brands: [
      'Pakton',
      'Urbanrove',
      'Alpine Carry',
      'Trekko',
      'Nomadic',
      'Carryall',
      'Terrago',
      'Packsmith',
    ],
    nameParts: [
      [
        'Travel',
        'Urban',
        'Canvas',
        'Leather',
        'Sport',
        'Laptop',
        'Anti-Theft',
        'Waterproof',
        'Slim',
        'Rolling',
      ],
      [
        'Backpack',
        'Tote',
        'Duffel',
        'Messenger',
        'Crossbody',
        'Sling',
        'Laptop Bag',
        'Weekender',
        'Clutch',
        'Briefcase',
      ],
    ],
    colors: ['Black', 'Navy', 'Olive', 'Grey', 'Brown', 'Tan', 'Red'],
    tags: ['bag', 'backpack', 'travel', 'laptop', 'tote', 'duffel'],
    specKeys: ['Material', 'Capacity', 'Laptop Compartment', 'Water Resistance', 'Dimensions'],
    specValues: {
      Material: ['Nylon', 'Canvas', 'Leather', 'Polyester', 'Cordura'],
      Capacity: ['10L', '15L', '20L', '25L', '30L', '35L', '40L'],
      'Laptop Compartment': ['Up to 13"', 'Up to 15"', 'Up to 17"', 'None'],
      'Water Resistance': ['Water-Resistant', 'Waterproof', 'Standard'],
      Dimensions: ['30x20x10cm', '40x28x15cm', '45x32x18cm', '50x35x20cm'],
    },
  },
  // 13 — Jewellery
  {
    name: 'Jewellery',
    subcategory: 'Accessories',
    priceRange: [15, 2200],
    brands: [
      'Aurum',
      'Brillante',
      'Silvara',
      'Gemara',
      'Claréo',
      'Lustral',
      'Novacarat',
      'Stellare',
    ],
    nameParts: [
      [
        'Diamond-Cut',
        'Gold-Plated',
        'Sterling Silver',
        'Rose Gold',
        'Minimalist',
        'Layered',
        'Statement',
        'Vintage',
        'Geometric',
        'Floral',
      ],
      [
        'Necklace',
        'Bracelet',
        'Ring',
        'Earrings',
        'Anklet',
        'Pendant',
        'Bangle',
        'Chain',
        'Stud',
        'Choker',
      ],
    ],
    colors: ['Gold', 'Silver', 'Rose Gold', 'Two-Tone', 'Black Gold'],
    tags: ['jewellery', 'gold', 'silver', 'necklace', 'ring', 'earrings', 'gift'],
    specKeys: ['Metal', 'Stone', 'Karat/Purity', 'Chain Length', 'Weight'],
    specValues: {
      Metal: [
        '925 Sterling Silver',
        '18K Gold Plated',
        '14K Solid Gold',
        'Rose Gold Plated',
        'Stainless Steel',
      ],
      Stone: ['Cubic Zirconia', 'Lab Diamond', 'Moissanite', 'Swarovski Crystal', 'No Stone'],
      'Karat/Purity': ['925 Sterling', '18K', '14K', '9K', 'Gold Vermeil'],
      'Chain Length': ['16 inch', '18 inch', '20 inch', '22 inch', 'Adjustable'],
      Weight: ['2g', '4g', '6g', '10g', '15g'],
    },
  },
  // 14 — Beauty & Cosmetics
  {
    name: 'Beauty & Cosmetics',
    subcategory: 'Beauty',
    priceRange: [8, 180],
    brands: [
      'Lumiglow',
      'Rosewater Lab',
      'Velvet Bloom',
      'Glow Theory',
      'Pure Luxe',
      'Botaniq',
      'Radiant Co.',
      'Skinveil',
    ],
    nameParts: [
      [
        'Hydrating',
        'Matte',
        'Glow',
        'Volumizing',
        'Long-Wear',
        'Natural',
        'Nourishing',
        'Brightening',
        'Smoothing',
        'Anti-Aging',
      ],
      [
        'Foundation',
        'Lipstick',
        'Mascara',
        'Eyeshadow',
        'Blush',
        'Concealer',
        'Primer',
        'Highlighter',
        'Palette',
        'Serum',
      ],
    ],
    colors: ['Fair', 'Light', 'Medium', 'Tan', 'Deep', 'Universal'],
    tags: ['beauty', 'cosmetics', 'makeup', 'skincare', 'vegan', 'cruelty-free'],
    specKeys: ['Coverage', 'Finish', 'Shade Range', 'Formula', 'Key Ingredient'],
    specValues: {
      Coverage: ['Sheer', 'Light', 'Medium', 'Full', 'Buildable'],
      Finish: ['Matte', 'Satin', 'Dewy', 'Luminous', 'Natural'],
      'Shade Range': ['12 shades', '24 shades', '30 shades', '40 shades'],
      Formula: ['Vegan', 'Cruelty-Free', 'Paraben-Free', 'Hypoallergenic'],
      'Key Ingredient': ['Hyaluronic Acid', 'Vitamin C', 'Retinol', 'Niacinamide', 'SPF 30'],
    },
  },
  // 15 — Perfumes
  {
    name: 'Perfumes',
    subcategory: 'Fragrance',
    priceRange: [28, 450],
    brands: [
      'Arôme',
      'Elixir Oud',
      'Botaniq Scents',
      'Veloura',
      'Luminos',
      'Parfumé',
      'Scentsara',
      'OudLux',
    ],
    nameParts: [
      [
        'Midnight',
        'Velvet',
        'Amber',
        'Rose',
        'Oud',
        'Aqua',
        'Cedar',
        'Neroli',
        'Saffron',
        'Jasmine',
      ],
      [
        'Essence',
        'Perfume',
        'Cologne',
        'EDP',
        'EDT',
        'Spray',
        'Parfum',
        'Scent',
        'Collection',
        'Edition',
      ],
    ],
    colors: ['50ml', '75ml', '100ml', '150ml', '200ml'],
    tags: ['perfume', 'fragrance', 'EDP', 'cologne', 'oud', 'luxury scent'],
    specKeys: ['Type', 'Concentration', 'Size', 'Top Notes', 'Heart Notes', 'Base Notes'],
    specValues: {
      Type: ['Eau de Parfum', 'Eau de Toilette', 'Parfum', 'Eau de Cologne', 'Aftershave'],
      Concentration: ['EDP 20%', 'EDT 10%', 'Parfum 25%', 'EDC 5%'],
      Size: ['30ml', '50ml', '75ml', '100ml', '150ml'],
      'Top Notes': [
        'Bergamot & Lemon',
        'Rose & Pepper',
        'Oud & Saffron',
        'Citrus & Ginger',
        'Aqua & Melon',
      ],
      'Heart Notes': ['Jasmine & Iris', 'Cedar & Amber', 'Vanilla & Musk', 'Sandalwood & Vetiver'],
      'Base Notes': ['Musk & Amber', 'Oud & Patchouli', 'Vanilla & Tonka', 'Cedar & Vetiver'],
    },
  },
  // 16 — Smartphones
  {
    name: 'Smartphones',
    subcategory: 'Mobile Phones',
    priceRange: [89, 1499],
    brands: [
      'Nexon',
      'Prism X',
      'Veltra',
      'Orbis',
      'Quantex Mobile',
      'NovaTech',
      'CorePhone',
      'ZenMobile',
    ],
    nameParts: [
      ['Pro', 'Ultra', 'Max', 'Lite', 'Plus', 'Edge', 'Neo', 'X', 'Nova', 'Apex'],
      ['Phone', 'Series', 'Edition', '5G', 'SE', 'Gen', 'Mobile', 'Smart', 'One', 'V'],
    ],
    colors: [
      'Midnight Black',
      'Pearl White',
      'Ocean Blue',
      'Titanium',
      'Forest Green',
      'Rose Gold',
    ],
    sizes: ['128GB', '256GB', '512GB', '1TB'],
    tags: ['smartphone', '5G', 'mobile', 'android', 'camera', 'tech'],
    specKeys: ['Display', 'Processor', 'RAM', 'Storage', 'Camera', 'Battery', 'OS'],
    specValues: {
      Display: ['6.1" OLED', '6.4" AMOLED', '6.7" Dynamic AMOLED', '6.8" LTPO OLED', '6.1" Retina'],
      Processor: [
        'Snapdragon 8 Gen 3',
        'Dimensity 9300',
        'A17 Pro',
        'Exynos 2400',
        'Snapdragon 7s Gen 2',
      ],
      RAM: ['8GB', '12GB', '16GB', '24GB'],
      Storage: ['128GB', '256GB', '512GB', '1TB'],
      Camera: ['50MP + 12MP + 10MP', '200MP + 50MP + 10MP', '48MP + 12MP', '108MP + 12MP + 5MP'],
      Battery: ['4000mAh', '4500mAh', '5000mAh', '5500mAh'],
      OS: ['Android 14', 'Android 15', 'iOS 17', 'iOS 18'],
    },
  },
  // 17 — Mobile Covers
  {
    name: 'Mobile Covers',
    subcategory: 'Phone Accessories',
    priceRange: [5, 65],
    brands: [
      'Shellguard',
      'CaseCraft',
      'ArmorX',
      'Slimshell',
      'Neocase',
      'Covertek',
      'Shockpro',
      'Lumishell',
    ],
    nameParts: [
      [
        'Clear',
        'Shockproof',
        'Leather',
        'Silicone',
        'Marble',
        'Floral',
        'Matte',
        'Rugged',
        'Slim',
        'Wallet',
      ],
      [
        'Case',
        'Cover',
        'Shield',
        'Back Cover',
        'Bumper',
        'Folio',
        'Protector',
        'Grip Case',
        'Wallet Case',
        'Clear Case',
      ],
    ],
    colors: ['Clear', 'Black', 'Blue', 'Red', 'Pink', 'Green', 'Marble White'],
    tags: ['phone case', 'cover', 'protection', 'mobile accessories', 'iPhone', 'Samsung'],
    specKeys: ['Compatible With', 'Material', 'Protection Level', 'Features'],
    specValues: {
      'Compatible With': [
        'iPhone 15 Pro',
        'iPhone 15',
        'Samsung S24 Ultra',
        'Samsung S24',
        'Pixel 8 Pro',
      ],
      Material: ['Polycarbonate', 'TPU', 'Leather', 'Silicone', 'Hard Plastic'],
      'Protection Level': ['Military Grade', 'Shockproof', 'Drop Protection', 'Basic'],
      Features: [
        'Magsafe Compatible',
        'Card Slot',
        'Kickstand',
        'Wireless Charging Compatible',
        'Screen Raised Edges',
      ],
    },
  },
  // 18 — Chargers
  {
    name: 'Chargers',
    subcategory: 'Power Accessories',
    priceRange: [9, 120],
    brands: [
      'Voltix',
      'Swiftcharge',
      'Powertek',
      'NexCharge',
      'Ampere One',
      'ChargePro',
      'Spark USB',
      'Watt+',
    ],
    nameParts: [
      ['Fast', '65W', '120W', '20W', '30W', 'Wireless', 'MagSafe', 'Multi-Port', 'GaN', 'Travel'],
      [
        'Charger',
        'Adapter',
        'Wall Charger',
        'Wireless Pad',
        'Power Adapter',
        'USB-C Charger',
        'Car Charger',
        'Charging Hub',
        'Dock',
        'Cable',
      ],
    ],
    tags: ['charger', 'USB-C', 'fast charging', 'GaN', 'wireless', 'power adapter'],
    specKeys: ['Output Power', 'Ports', 'Cable Included', 'Compatible Protocols', 'Form Factor'],
    specValues: {
      'Output Power': ['18W', '20W', '30W', '45W', '65W', '100W', '120W'],
      Ports: ['1x USB-C', '2x USB-C', '1x USB-C + 2x USB-A', '3x USB-C', '4 Ports'],
      'Cable Included': ['Yes - USB-C to C', 'Yes - USB-C to Lightning', 'No', 'Yes - Micro USB'],
      'Compatible Protocols': ['USB PD', 'PD 3.0 + QC 4+', 'MagSafe', 'GaN Tech', 'QC 3.0'],
      'Form Factor': ['Compact Cube', 'Foldable Plug', 'UK Plug', 'EU Plug', 'Universal'],
    },
  },
  // 19 — Earbuds
  {
    name: 'Earbuds',
    subcategory: 'Audio',
    priceRange: [19, 320],
    brands: [
      'SoundCore',
      'AuraBeats',
      'Nexaudio',
      'ClearPod',
      'WaveSync',
      'DeepBass Co.',
      'AirPure',
      'ToneTech',
    ],
    nameParts: [
      ['Pro', 'Lite', 'Air', 'Bass', 'Active', 'Nano', 'Ultra', 'True', 'Sport', 'Plus'],
      ['Buds', 'Pods', 'Earbuds', 'TWS', 'Series', 'Edition', 'Wireless', 'ANC', 'Pro', 'Fit'],
    ],
    colors: ['Black', 'White', 'Navy', 'Rose', 'Sage Green'],
    tags: ['earbuds', 'TWS', 'ANC', 'wireless', 'audio', 'music'],
    specKeys: ['Driver Size', 'ANC', 'Battery Life', 'Charging Case', 'Water Rating', 'Codec'],
    specValues: {
      'Driver Size': ['6mm', '8mm', '10mm', '11mm', '12mm'],
      ANC: ['Yes - Active Noise Cancelling', 'No', 'Transparency Mode Only'],
      'Battery Life': ['5h + 15h case', '6h + 24h case', '8h + 32h case', '10h + 40h case'],
      'Charging Case': ['USB-C', 'Wireless + USB-C', 'Lightning'],
      'Water Rating': ['IPX4', 'IPX5', 'IPX7'],
      Codec: ['AAC', 'aptX', 'LDAC', 'aptX Adaptive'],
    },
  },
  // 20 — Headphones
  {
    name: 'Headphones',
    subcategory: 'Audio',
    priceRange: [25, 550],
    brands: [
      'Aural Pro',
      'SonicBand',
      'BassForge',
      'Clarix',
      'DepthSound',
      'Resonance',
      'NoiseFree',
      'HiFiCraft',
    ],
    nameParts: [
      [
        'Studio',
        'Bass',
        'Pro',
        'Ultra',
        'Elite',
        'Classic',
        'Active',
        'Wireless',
        'Foldable',
        'Open-Back',
      ],
      [
        'Headphones',
        'Cans',
        'Over-Ear',
        'On-Ear',
        'Monitor',
        'Series',
        'Edition',
        'ANC',
        'HiFi',
        'Planar',
      ],
    ],
    colors: ['Black', 'White', 'Silver', 'Midnight Blue', 'Champagne'],
    tags: ['headphones', 'over-ear', 'ANC', 'wireless', 'studio', 'HiFi'],
    specKeys: ['Driver', 'ANC', 'Battery', 'Frequency Response', 'Impedance', 'Microphone'],
    specValues: {
      Driver: ['40mm Dynamic', '40mm Planar Magnetic', '45mm Dynamic', '50mm Dynamic'],
      ANC: ['Adaptive ANC', 'Hybrid ANC', 'None', 'Transparency Mode'],
      Battery: ['20h', '30h', '40h', '60h', '70h (ANC off)'],
      'Frequency Response': ['20Hz-20kHz', '10Hz-22kHz', '5Hz-40kHz'],
      Impedance: ['32Ω', '64Ω', '150Ω', '300Ω'],
      Microphone: ['Built-In', 'Detachable', 'None'],
    },
  },
  // 21 — Laptops
  {
    name: 'Laptops',
    subcategory: 'Computers',
    priceRange: [299, 3200],
    brands: [
      'Novex',
      'AlphaBook',
      'CorePro',
      'StellarPC',
      'AeroBook',
      'TechEdge',
      'QuantumBook',
      'ApexPro',
    ],
    nameParts: [
      [
        'Pro',
        'Ultra',
        'Air',
        'Studio',
        'Creator',
        'Gaming',
        'Business',
        'Essential',
        'Max',
        'Slim',
      ],
      ['Book', 'Laptop', 'Pro', 'Air', 'Notebook', 'Studio', 'Series', 'Edition', 'One', 'X'],
    ],
    colors: ['Space Grey', 'Silver', 'Black', 'Gold', 'Midnight Blue'],
    sizes: ['13 inch', '14 inch', '15.6 inch', '16 inch', '17 inch'],
    tags: ['laptop', 'notebook', 'computer', 'ultrabook', 'gaming', 'work'],
    specKeys: ['Processor', 'RAM', 'Storage', 'Display', 'GPU', 'Battery', 'OS'],
    specValues: {
      Processor: [
        'Intel Core i5-13th',
        'Intel Core i7-13th',
        'Intel Core i9-14th',
        'AMD Ryzen 7 7840',
        'Apple M3',
        'Apple M3 Pro',
      ],
      RAM: ['8GB', '16GB', '32GB', '64GB'],
      Storage: ['256GB SSD', '512GB SSD', '1TB SSD', '2TB SSD'],
      Display: ['13.3" FHD IPS', '14" 2K IPS', '15.6" FHD 144Hz', '16" Retina', '17" 4K OLED'],
      GPU: [
        'Intel Iris Xe',
        'NVIDIA RTX 4060',
        'NVIDIA RTX 4070',
        'AMD Radeon RX 7600M',
        'Apple M3 GPU',
      ],
      Battery: ['8h', '12h', '15h', '18h', '22h'],
      OS: ['Windows 11', 'macOS Sonoma', 'Linux', 'Chrome OS'],
    },
  },
  // 22 — Tablets
  {
    name: 'Tablets',
    subcategory: 'Computers',
    priceRange: [89, 1300],
    brands: [
      'TabX',
      'NexPad',
      'CoreSlate',
      'Veltra Tab',
      'PixelPad',
      'SmartTab',
      'ProPad',
      'EliteSlate',
    ],
    nameParts: [
      ['Pro', 'Air', 'Lite', 'Ultra', 'Smart', 'Mini', 'Plus', 'Max', 'Active', 'Note'],
      ['Tab', 'Pad', 'Slate', 'Tablet', 'Series', 'Edition', 'One', 'Studio', 'Book', 'Duo'],
    ],
    colors: ['Space Grey', 'Silver', 'Black', 'Blue', 'Green'],
    sizes: ['64GB', '128GB', '256GB', '512GB'],
    tags: ['tablet', 'iPad', 'Android tablet', 'drawing', 'productivity', 'kids tablet'],
    specKeys: ['Display', 'Processor', 'RAM', 'Storage', 'Battery', 'Stylus Support', 'OS'],
    specValues: {
      Display: [
        '8" IPS LCD',
        '10.2" Retina',
        '10.9" LCD',
        '11" OLED',
        '12.9" Mini-LED',
        '13" OLED',
      ],
      Processor: ['A15 Bionic', 'Snapdragon 8 Gen 2', 'Dimensity 9000', 'Tensor G3', 'A14 Bionic'],
      RAM: ['4GB', '6GB', '8GB', '12GB', '16GB'],
      Storage: ['64GB', '128GB', '256GB', '512GB', '1TB'],
      Battery: ['5000mAh', '7000mAh', '8000mAh', '10000mAh'],
      'Stylus Support': ['Yes', 'No'],
      OS: ['iPadOS 17', 'Android 14', 'Android 15', 'Windows 11'],
    },
  },
  // 23 — Gaming
  {
    name: 'Gaming',
    subcategory: 'Gaming Gear',
    priceRange: [15, 1800],
    brands: [
      'Nexon Gaming',
      'Hyperblast',
      'ArenaFX',
      'ProRig',
      'SteelForge',
      'QuestGear',
      'GameVault',
      'RigCore',
    ],
    nameParts: [
      [
        'Mechanical',
        'RGB',
        'Pro',
        'Ultra',
        'Wireless',
        'Hyper',
        'Gaming',
        'Precision',
        'Raptor',
        'Stealth',
      ],
      [
        'Keyboard',
        'Mouse',
        'Headset',
        'Controller',
        'Monitor',
        'Chair',
        'Desk',
        'GPU',
        'Console',
        'Mousepad',
      ],
    ],
    colors: ['Black/RGB', 'White/RGB', 'Black', 'Red/Black', 'Blue/Black'],
    tags: ['gaming', 'RGB', 'mechanical keyboard', 'gaming mouse', 'esports', 'PC gaming'],
    specKeys: ['Type', 'Connection', 'Switch Type', 'DPI / Refresh Rate', 'RGB', 'Compatibility'],
    specValues: {
      Type: ['Keyboard', 'Mouse', 'Headset', 'Controller', 'Monitor', 'Chair'],
      Connection: ['Wired USB', '2.4GHz Wireless', 'Bluetooth', 'Wired + Wireless'],
      'Switch Type': ['Linear Red', 'Tactile Brown', 'Clicky Blue', 'Speed Silver', 'N/A'],
      'DPI / Refresh Rate': [
        'Up to 16000 DPI',
        'Up to 25000 DPI',
        '144Hz',
        '165Hz',
        '240Hz',
        '360Hz',
      ],
      RGB: ['Yes - Per-Key RGB', 'Yes - Zone RGB', 'No'],
      Compatibility: ['PC', 'PC & Console', 'PS5', 'Xbox', 'Multi-Platform'],
    },
  },
  // 24 — Home Decor
  {
    name: 'Home Decor',
    subcategory: 'Interior',
    priceRange: [8, 650],
    brands: [
      'Ornara',
      'Vivendi Home',
      'Luma Deco',
      'Craftique',
      'NestCraft',
      'Homedge',
      'Décorova',
      'Luminal Home',
    ],
    nameParts: [
      [
        'Minimalist',
        'Nordic',
        'Boho',
        'Vintage',
        'Modern',
        'Rustic',
        'Scandinavian',
        'Art Deco',
        'Coastal',
        'Industrial',
      ],
      [
        'Vase',
        'Wall Art',
        'Mirror',
        'Candle',
        'Frame',
        'Sculpture',
        'Cushion',
        'Rug',
        'Clock',
        'Lamp',
      ],
    ],
    colors: ['White', 'Beige', 'Black', 'Gold', 'Natural Wood', 'Terracotta'],
    tags: ['home decor', 'interior', 'living room', 'bedroom', 'minimal', 'aesthetic'],
    specKeys: ['Material', 'Dimensions', 'Style', 'Care'],
    specValues: {
      Material: ['Ceramic', 'Glass', 'Wood', 'Metal', 'Resin', 'Marble', 'Cotton', 'Rattan'],
      Dimensions: [
        'Small (under 20cm)',
        'Medium (20-40cm)',
        'Large (40-80cm)',
        'Extra Large (80cm+)',
      ],
      Style: ['Minimalist', 'Boho', 'Nordic', 'Industrial', 'Traditional'],
      Care: ['Wipe Clean', 'Dust Regularly', 'Avoid Direct Sunlight', 'Hand Wash'],
    },
  },
  // 25 — Furniture
  {
    name: 'Furniture',
    subcategory: 'Home Furniture',
    priceRange: [45, 3500],
    brands: [
      'Woodcraft Home',
      'Scandique',
      'Urbanspace',
      'Nestoria',
      'Solidform',
      'Modulo',
      'Artisano',
      'Homecrest',
    ],
    nameParts: [
      [
        'Solid Wood',
        'Nordic',
        'Modern',
        'Minimalist',
        'Industrial',
        'Velvet',
        'Rattan',
        'Storage',
        'Foldable',
        'Space-Saving',
      ],
      [
        'Sofa',
        'Chair',
        'Table',
        'Desk',
        'Shelf',
        'Bookcase',
        'Bed Frame',
        'Wardrobe',
        'Cabinet',
        'Bench',
      ],
    ],
    colors: ['Natural Oak', 'Walnut', 'White', 'Black', 'Grey', 'Beige'],
    tags: ['furniture', 'sofa', 'chair', 'table', 'desk', 'home', 'living room'],
    specKeys: ['Material', 'Dimensions', 'Weight Capacity', 'Assembly', 'Style'],
    specValues: {
      Material: [
        'Solid Oak',
        'MDF + Veneer',
        'Solid Walnut',
        'Metal Frame + Upholstery',
        'Bamboo',
        'Rattan',
      ],
      Dimensions: [
        '2-Seater: 150x85x90cm',
        '3-Seater: 210x90x85cm',
        'Coffee Table: 100x50x45cm',
        'Dining Table: 180x90cm',
      ],
      'Weight Capacity': ['80kg', '120kg', '150kg', '200kg', '250kg'],
      Assembly: ['Self-Assembly', 'Professional Assembly Recommended', 'No Assembly Required'],
      Style: ['Scandinavian', 'Industrial', 'Mid-Century', 'Contemporary', 'Traditional'],
    },
  },
  // 26 — Kitchen
  {
    name: 'Kitchen',
    subcategory: 'Kitchenware',
    priceRange: [8, 850],
    brands: [
      'ChefLine',
      'CulinoCraft',
      'KitchenPro',
      'IronChef',
      'NovaCook',
      'MasterPan',
      'GourmetEdge',
      'PrecisionCook',
    ],
    nameParts: [
      [
        'Cast Iron',
        'Non-Stick',
        'Stainless Steel',
        'Ceramic',
        'Smart',
        'Professional',
        'Premium',
        'Essential',
        'Classic',
        'Modern',
      ],
      [
        'Pan',
        'Pot',
        'Knife',
        'Blender',
        'Air Fryer',
        'Knife Set',
        'Cutting Board',
        'Cookware Set',
        'Wok',
        'Kettle',
      ],
    ],
    tags: ['kitchen', 'cookware', 'knives', 'appliances', 'cooking', 'baking'],
    specKeys: ['Material', 'Dimensions', 'Oven Safe', 'Dishwasher Safe', 'Induction Compatible'],
    specValues: {
      Material: [
        'Cast Iron',
        'Stainless Steel',
        'Hard-Anodized Aluminium',
        'Ceramic Coated',
        'Carbon Steel',
      ],
      Dimensions: ['20cm', '24cm', '26cm', '28cm', '30cm', '32cm'],
      'Oven Safe': ['Yes, up to 200°C', 'Yes, up to 260°C', 'No'],
      'Dishwasher Safe': ['Yes', 'No - Hand Wash Only'],
      'Induction Compatible': ['Yes', 'No', 'Universal (All Hobs)'],
    },
  },
  // 27 — Lighting
  {
    name: 'Lighting',
    subcategory: 'Home Lighting',
    priceRange: [12, 480],
    brands: [
      'Luminos',
      'BrightHome',
      'GlowCraft',
      'LedLux',
      'Sunbeam Home',
      'LampCo',
      'LumiArc',
      'Illumos',
    ],
    nameParts: [
      [
        'LED',
        'Smart',
        'Dimmable',
        'Solar',
        'Pendant',
        'Floor',
        'Table',
        'Ceiling',
        'Strip',
        'Outdoor',
      ],
      [
        'Lamp',
        'Light',
        'Bulb',
        'Fixture',
        'Strip Light',
        'Chandelier',
        'Downlight',
        'Spotlight',
        'Lantern',
        'Panel',
      ],
    ],
    colors: ['Warm White', 'Cool White', 'RGB', 'Neutral White', 'Natural'],
    tags: ['lighting', 'LED', 'smart light', 'lamp', 'home', 'energy saving'],
    specKeys: ['Wattage', 'Lumen Output', 'Colour Temperature', 'Smart Control', 'Lifespan'],
    specValues: {
      Wattage: ['4W', '8W', '12W', '18W', '25W', '40W'],
      'Lumen Output': ['400lm', '800lm', '1100lm', '1600lm', '2400lm'],
      'Colour Temperature': [
        '2700K Warm White',
        '3000K Warm White',
        '4000K Neutral',
        '5000K Daylight',
        '6500K Cool White',
      ],
      'Smart Control': ['App + Voice', 'App Only', 'Dimmable Switch', 'Standard'],
      Lifespan: ['15,000 hours', '20,000 hours', '25,000 hours', '30,000 hours'],
    },
  },
  // 28 — Smart Home
  {
    name: 'Smart Home',
    subcategory: 'IoT & Automation',
    priceRange: [15, 650],
    brands: [
      'Nexhome',
      'AutoDwell',
      'SmartNest',
      'ConnectHome',
      'IoTech',
      'HomeSense',
      'SmartLink',
      'EcoDwell',
    ],
    nameParts: [
      [
        'Smart',
        'Wi-Fi',
        'Voice-Controlled',
        'Auto',
        'Intelligent',
        'Connected',
        'AI-Powered',
        'Energy-Saving',
        'Universal',
        'Wireless',
      ],
      [
        'Thermostat',
        'Door Lock',
        'Camera',
        'Doorbell',
        'Plug',
        'Light Switch',
        'Speaker',
        'Hub',
        'Sensor',
        'Alarm',
      ],
    ],
    tags: ['smart home', 'IoT', 'Alexa', 'Google Home', 'automation', 'security'],
    specKeys: ['Compatibility', 'Connectivity', 'Power', 'Installation', 'App Control'],
    specValues: {
      Compatibility: [
        'Alexa + Google Home',
        'Apple HomeKit',
        'Matter Standard',
        'Zigbee',
        'Universal',
      ],
      Connectivity: ['Wi-Fi 2.4GHz', 'Wi-Fi 2.4+5GHz', 'Zigbee', 'Z-Wave', 'Bluetooth + Wi-Fi'],
      Power: ['Battery Powered', 'Mains Powered', 'USB-C', 'Hardwired'],
      Installation: ['DIY - No Wiring', 'DIY - Basic Wiring', 'Professional Required'],
      'App Control': ['Yes - iOS & Android', 'Yes - iOS Only', 'Yes - Android Only'],
    },
  },
  // 29 — Sports & Fitness
  {
    name: 'Sports & Fitness',
    subcategory: 'Exercise',
    priceRange: [10, 1200],
    brands: [
      'IronFlex',
      'MaxRep',
      'FitCore',
      'AthletePro',
      'PowerEdge',
      'Flexforce',
      'GainGear',
      'StrideMax',
    ],
    nameParts: [
      [
        'Pro',
        'Heavy Duty',
        'Adjustable',
        'Foldable',
        'Commercial',
        'Home',
        'Resistance',
        'High-Intensity',
        'Compact',
        'Multi-Function',
      ],
      [
        'Dumbbells',
        'Barbell',
        'Resistance Bands',
        'Yoga Mat',
        'Treadmill',
        'Jump Rope',
        'Kettlebell',
        'Pull-Up Bar',
        'Bench',
        'Foam Roller',
      ],
    ],
    colors: ['Black', 'Grey', 'Blue', 'Red', 'Green'],
    tags: ['fitness', 'gym', 'workout', 'exercise', 'yoga', 'weights'],
    specKeys: ['Weight / Resistance', 'Material', 'Max User Weight', 'Dimensions', 'Warranty'],
    specValues: {
      'Weight / Resistance': ['5kg', '10kg', '15kg', '20kg', '25kg', '50kg', '100kg'],
      Material: ['Rubber Coated Cast Iron', 'Chrome Steel', 'Foam + TPE', 'PVC', 'Neoprene'],
      'Max User Weight': ['100kg', '120kg', '150kg', '200kg', '250kg'],
      Dimensions: ['Compact', 'Standard', 'Large', 'Foldable'],
      Warranty: ['1 Year', '2 Years', '5 Years', 'Lifetime'],
    },
  },
  // 30 — Toys & Games
  {
    name: 'Toys & Games',
    subcategory: 'Toys',
    priceRange: [6, 280],
    brands: [
      'Playvox',
      'Wondercraft',
      'Brainblock',
      'TinyWorld',
      'JoyZone',
      'Funspark',
      'Buildio',
      'Kidventure',
    ],
    nameParts: [
      [
        'STEM',
        'Creative',
        'Interactive',
        'Educational',
        'Remote Control',
        'Plush',
        'Wooden',
        'Magnetic',
        'Building',
        'Outdoor',
      ],
      [
        'Toy',
        'Puzzle',
        'Board Game',
        'Block Set',
        'Action Figure',
        'Doll',
        'Car',
        'Robot',
        'Craft Kit',
        'Science Kit',
      ],
    ],
    colors: ['Multicolor', 'Blue', 'Red', 'Yellow', 'Green', 'Pink'],
    sizes: ['3+', '5+', '7+', '10+', '12+', '14+'],
    tags: ['toys', 'games', 'kids', 'educational', 'STEM', 'board game'],
    specKeys: [
      'Age Range',
      'Number of Players',
      'Material',
      'Battery Required',
      'Learning Outcome',
    ],
    specValues: {
      'Age Range': ['3-5 Years', '5-8 Years', '8-12 Years', '12+ Years', 'All Ages'],
      'Number of Players': ['1', '2-4', '2-6', '2-8'],
      Material: ['ABS Plastic', 'Wood', 'Fabric', 'Cardboard', 'Metal'],
      'Battery Required': ['Yes - AA x3', 'Yes - AAA x4', 'Yes - USB Charged', 'No'],
      'Learning Outcome': [
        'STEM Skills',
        'Creativity',
        'Motor Skills',
        'Social Skills',
        'Problem Solving',
      ],
    },
  },
  // 31 — Books
  {
    name: 'Books',
    subcategory: 'Books & Media',
    priceRange: [5, 65],
    brands: [
      'Inkwell Press',
      'Narrative House',
      'Luminary Books',
      'Voxa',
      'Pagecraft',
      'Readmark',
      'Verso',
      'Chapters',
    ],
    nameParts: [
      [
        'The Art of',
        'Mastering',
        'Complete Guide to',
        'Introduction to',
        'The Science of',
        'Stories of',
        'Ultimate',
        'Modern',
        'Classic',
        'Essential',
      ],
      [
        'Business',
        'Leadership',
        'Creativity',
        'Mindfulness',
        'Cooking',
        'Travel',
        'History',
        'Fiction',
        'Self-Help',
        'Design',
      ],
    ],
    tags: ['book', 'reading', 'bestseller', 'fiction', 'non-fiction', 'self-help'],
    specKeys: ['Format', 'Pages', 'Genre', 'Language', 'Publisher'],
    specValues: {
      Format: ['Hardcover', 'Paperback', 'eBook', 'Audiobook'],
      Pages: ['150-250', '250-400', '400-600', '600+'],
      Genre: [
        'Fiction',
        'Non-Fiction',
        'Self-Help',
        'Biography',
        'Science',
        'History',
        'Business',
        'Fantasy',
      ],
      Language: ['English', 'Bilingual'],
      Publisher: ['Inkwell Press', 'Narrative House', 'Luminary Books'],
    },
  },
  // 32 — Automotive
  {
    name: 'Automotive',
    subcategory: 'Auto Parts',
    priceRange: [8, 1200],
    brands: [
      'AutoXcel',
      'DriveMax',
      'TurboEdge',
      'PrecisionAuto',
      'OEM Plus',
      'MotorCraft',
      'DriveTech',
      'CarCore',
    ],
    nameParts: [
      [
        'Performance',
        'Heavy Duty',
        'OEM Grade',
        'Universal',
        'High-Flow',
        'Premium',
        'Sport',
        'Heavy Duty',
        'Original',
        'Racing',
      ],
      [
        'Brake Pads',
        'Air Filter',
        'Oil Filter',
        'Spark Plug',
        'Wiper Blade',
        'LED Headlight',
        'Exhaust Tip',
        'Seat Cover',
        'Floor Mat',
        'Dash Cam',
      ],
    ],
    tags: ['automotive', 'car parts', 'auto accessories', 'performance', 'OEM', 'vehicle'],
    specKeys: ['Compatibility', 'Material', 'Installation', 'Warranty', 'Part Number'],
    specValues: {
      Compatibility: [
        'Universal Fit',
        'Toyota Specific',
        'BMW Specific',
        'Ford Specific',
        'Honda Specific',
      ],
      Material: ['Steel', 'Aluminium', 'Ceramic', 'Carbon Fibre', 'Rubber'],
      Installation: ['DIY', 'Professional Installation', 'Plug & Play'],
      Warranty: ['6 Months', '1 Year', '2 Years', '3 Years'],
      'Part Number': ['Refer to manual', 'Universal'],
    },
  },
  // 33 — Car Accessories
  {
    name: 'Car Accessories',
    subcategory: 'Vehicle Accessories',
    priceRange: [6, 380],
    brands: [
      'CarElite',
      'DriveGear',
      'AutoComfort',
      'RoadKit',
      'CarTech',
      'Drives+',
      'VehiclePro',
      'MotorEase',
    ],
    nameParts: [
      [
        '360°',
        'Wireless',
        'Universal',
        'Dash',
        'Premium',
        'Smart',
        'Portable',
        'Heavy Duty',
        'Fast',
        'Compact',
      ],
      [
        'Phone Mount',
        'Dash Cam',
        'Car Charger',
        'Seat Organizer',
        'Air Freshener',
        'Sunshade',
        'Parking Sensor',
        'Vacuum',
        'GPS',
        'Jump Starter',
      ],
    ],
    tags: ['car accessories', 'dash cam', 'phone mount', 'car charger', 'GPS', 'driving'],
    specKeys: ['Compatibility', 'Power Source', 'Features', 'Installation Type'],
    specValues: {
      Compatibility: ['Universal', 'iPhone & Android', 'All Vehicles', 'Specific Mount'],
      'Power Source': ['12V Lighter', 'USB-C', 'Hardwired', 'Battery'],
      Features: [
        'GPS Tracking',
        'Night Vision',
        '4K Recording',
        'Parking Mode',
        'App Connectivity',
      ],
      'Installation Type': ['Magnetic Mount', 'Suction Cup', 'Dashboard Adhesive', 'Vent Mount'],
    },
  },
  // 34 — Travel Accessories
  {
    name: 'Travel Accessories',
    subcategory: 'Travel',
    priceRange: [5, 250],
    brands: [
      'Roamcraft',
      'Globetrotter',
      'TravelSmart',
      'Jetpack',
      'Nomad Gear',
      'Wayfare',
      'TravelPro',
      'Packwise',
    ],
    nameParts: [
      [
        'Anti-Theft',
        'Compact',
        'Waterproof',
        'Convertible',
        'Universal',
        'RFID',
        'TSA-Approved',
        'Packing',
        'Multi-Purpose',
        'Travel',
      ],
      [
        'Pillow',
        'Luggage',
        'Packing Cube',
        'Passport Holder',
        'Neck Pillow',
        'Lock',
        'Adapter',
        'Toiletry Bag',
        'Money Belt',
        'Sleep Mask',
      ],
    ],
    tags: ['travel', 'luggage', 'packing', 'airport', 'holiday', 'backpacking'],
    specKeys: ['Dimensions', 'Material', 'TSA Approved', 'Capacity', 'Features'],
    specValues: {
      Dimensions: ['Small (Cabin)', 'Medium (Hold)', 'Large (Hold)', 'Extra Large'],
      Material: ['Polycarbonate', 'ABS', 'Nylon', 'Polyester', 'Aluminium'],
      'TSA Approved': ['Yes', 'No'],
      Capacity: ['20L', '40L', '55L', '70L', '90L'],
      Features: ['Spinner Wheels', 'Hardshell', 'Expandable', 'USB Port', 'Tracking Device'],
    },
  },
  // 35 — Office Supplies
  {
    name: 'Office Supplies',
    subcategory: 'Stationery',
    priceRange: [3, 320],
    brands: [
      'OfficeEdge',
      'Destaque',
      'Papilio',
      'InkMark',
      'DeskCraft',
      'Statix',
      'Pencraft',
      'Workset',
    ],
    nameParts: [
      [
        'Ergonomic',
        'Premium',
        'Professional',
        'Smart',
        'Portable',
        'Heavy Duty',
        'Eco-Friendly',
        'Wireless',
        'Compact',
        'Multi-Function',
      ],
      [
        'Notebook',
        'Pen Set',
        'Desk Organizer',
        'Monitor Stand',
        'Keyboard',
        'Mouse Pad',
        'Stapler',
        'Planner',
        'Whiteboard',
        'Label Maker',
      ],
    ],
    tags: ['office', 'stationery', 'desk', 'work from home', 'productivity', 'ergonomic'],
    specKeys: ['Material', 'Pages / Capacity', 'Compatibility', 'Dimensions', 'Features'],
    specValues: {
      Material: ['Leather-Bound', 'Hardcover', 'Recycled Paper', 'Aluminium', 'Plastic'],
      'Pages / Capacity': ['100 pages', '200 pages', 'A4', 'A5'],
      Compatibility: ['Universal', 'Mac & PC', 'Windows Only'],
      Dimensions: ['A4', 'A5', 'A6', 'Standard', 'Large'],
      Features: ['Dotted Grid', 'Lined', 'Blank', 'Index', 'Perforated Pages'],
    },
  },
  // 36 — Pet Supplies
  {
    name: 'Pet Supplies',
    subcategory: 'Pets',
    priceRange: [5, 280],
    brands: [
      'PawLux',
      'FurCraft',
      'PetCore',
      'TailWag',
      'PetComfort',
      'ZooPro',
      'Petify',
      'Animalia',
    ],
    nameParts: [
      [
        'Premium',
        'Natural',
        'Organic',
        'Interactive',
        'Anti-Anxiety',
        'Orthopedic',
        'Travel',
        'Waterproof',
        'Adjustable',
        'Luxury',
      ],
      [
        'Dog Bed',
        'Cat Tree',
        'Collar',
        'Leash',
        'Food Bowl',
        'Toy',
        'Carrier',
        'Harness',
        'Grooming Kit',
        'Feeder',
      ],
    ],
    colors: ['Black', 'Blue', 'Pink', 'Grey', 'Brown', 'Red'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    tags: ['pet', 'dog', 'cat', 'pet accessories', 'grooming', 'animal'],
    specKeys: ['For', 'Material', 'Size', 'Washable', 'Features'],
    specValues: {
      For: ['Dogs', 'Cats', 'Dogs & Cats', 'Small Pets'],
      Material: ['Oxford Fabric', 'Memory Foam', 'Fleece', 'Nylon', 'Stainless Steel'],
      Size: ['XS (0-5kg)', 'S (5-10kg)', 'M (10-20kg)', 'L (20-35kg)', 'XL (35kg+)'],
      Washable: ['Machine Washable', 'Hand Wash Only', 'Wipe Clean'],
      Features: ['Non-Slip Bottom', 'Removable Cover', 'Chew-Resistant', 'Waterproof'],
    },
  },
  // 37 — Grocery
  {
    name: 'Grocery',
    subcategory: 'Food & Drink',
    priceRange: [2, 80],
    brands: [
      'Naturelle',
      'OrganicHarvest',
      'FreshPick',
      'PureGrain',
      'TasteNest',
      'GreenLeaf',
      'HarvestCo.',
      'EarthKind',
    ],
    nameParts: [
      [
        'Organic',
        'Artisan',
        'Premium',
        'Natural',
        'Wholesome',
        'Farm-Fresh',
        'Cold-Pressed',
        'Raw',
        'Aged',
        'Craft',
      ],
      [
        'Olive Oil',
        'Honey',
        'Coffee Beans',
        'Tea Selection',
        'Granola',
        'Pasta',
        'Rice',
        'Nuts & Seeds',
        'Spice Blend',
        'Chocolate',
      ],
    ],
    tags: ['grocery', 'food', 'organic', 'natural', 'healthy', 'pantry'],
    specKeys: ['Weight / Volume', 'Organic', 'Allergens', 'Country of Origin', 'Shelf Life'],
    specValues: {
      'Weight / Volume': ['100g', '250g', '500g', '1kg', '2kg', '500ml', '1L'],
      Organic: ['Certified Organic', 'Natural', 'Non-GMO', 'Conventional'],
      Allergens: ['Gluten-Free', 'Nut-Free', 'Dairy-Free', 'Vegan', 'Contains Nuts'],
      'Country of Origin': ['Italy', 'Greece', 'Spain', 'USA', 'India', 'Japan'],
      'Shelf Life': ['6 months', '12 months', '18 months', '24 months'],
    },
  },
  // 38 — Health & Wellness
  {
    name: 'Health & Wellness',
    subcategory: 'Wellbeing',
    priceRange: [8, 320],
    brands: [
      'VitaCore',
      'WellEdge',
      'NutriMax',
      'PureForm',
      'BioBalance',
      'ZenBody',
      'SupraVita',
      'HolisticCo.',
    ],
    nameParts: [
      [
        'Daily',
        'Advanced',
        'Premium',
        'Vegan',
        'Ultra',
        'Natural',
        'Clinical',
        'Essential',
        'Pro',
        'Organic',
      ],
      [
        'Vitamin D3',
        'Omega-3',
        'Probiotic',
        'Protein Powder',
        'Collagen',
        'Zinc Supplement',
        'Multivitamin',
        'Sleep Aid',
        'Turmeric',
        'Biotin',
      ],
    ],
    tags: ['health', 'wellness', 'vitamins', 'supplements', 'protein', 'vegan'],
    specKeys: ['Servings', 'Key Ingredients', 'Form', 'Dietary', 'Certifications'],
    specValues: {
      Servings: ['30 servings', '60 servings', '90 servings', '120 servings'],
      'Key Ingredients': [
        'Vitamin D3 + K2',
        'EPA & DHA',
        'Lactobacillus',
        'Whey Protein',
        'Hydrolysed Collagen',
      ],
      Form: ['Capsules', 'Gummies', 'Powder', 'Liquid', 'Tablets'],
      Dietary: ['Vegan', 'Vegetarian', 'Gluten-Free', 'Non-GMO', 'Keto-Friendly'],
      Certifications: ['GMP Certified', 'NSF Certified', 'Informed Sport', 'ISO 9001'],
    },
  },
  // 39 — Gift Items
  {
    name: 'Gift Items',
    subcategory: 'Gifts',
    priceRange: [12, 450],
    brands: [
      'Giftcraft',
      'Luxebox',
      'WrapCo',
      'Memorique',
      'Cherish',
      'PresentPlus',
      'GiftSmith',
      'Sentiments Co.',
    ],
    nameParts: [
      [
        'Personalized',
        'Luxury',
        'Handcrafted',
        'Premium',
        'Custom',
        'Engraved',
        'Anniversary',
        'Birthday',
        'Holiday',
        'Curated',
      ],
      [
        'Gift Set',
        'Hamper',
        'Candle',
        'Journal',
        'Photo Frame',
        'Keepsake Box',
        'Mug',
        'Jewellery Box',
        'Wine Set',
        'Experience Voucher',
      ],
    ],
    colors: ['Gold', 'Rose Gold', 'Silver', 'Black', 'White'],
    tags: ['gift', 'present', 'birthday', 'anniversary', 'luxury gift', 'personalised'],
    specKeys: ['Occasion', 'Includes', 'Personalisation', 'Packaging', 'For'],
    specValues: {
      Occasion: [
        'Birthday',
        'Anniversary',
        'Wedding',
        'Christmas',
        "Valentine's Day",
        "Mother's Day",
        "Father's Day",
      ],
      Includes: ['Gift Box', 'Ribbon', 'Gift Card', 'Tissue Paper'],
      Personalisation: ['Engravable', 'Printable', 'Custom Text', 'None'],
      Packaging: ['Premium Gift Box', 'Ribbon Wrapped', 'Eco Kraft Box', 'Luxury Bag'],
      For: ['For Her', 'For Him', 'For Kids', 'Unisex'],
    },
  },
]

// ── Product factory ──────────────────────────────────────────────────────────
function makeProducts(cat: CatDef, catIndex: number): CatalogProduct[] {
  const products: CatalogProduct[] = []
  const [adjs, nouns] = cat.nameParts

  for (let i = 0; i < 100; i++) {
    const globalSeed = catIndex * 100 + i
    const adj = adjs[i % adjs.length]
    const noun = nouns[i % nouns.length]
    const brandIndex = (i * 3 + catIndex) % cat.brands.length
    const brand = cat.brands[brandIndex]

    // Vary names to avoid repetition
    const suffix = i < adjs.length ? '' : i < adjs.length * 2 ? ` ${i + 1}` : ` ${brand}`
    const name = `${adj} ${noun}${suffix}`.replace('  ', ' ').trim()

    const [minP, maxP] = cat.priceRange
    const t = ((globalSeed * 17 + 7) % 100) / 100
    const basePrice = Math.round(lerp(minP, maxP, t) * 100) / 100
    const disc = discount(globalSeed)
    const originalPrice = disc ? Math.round(basePrice / (1 - disc / 100)) : undefined
    const price = originalPrice ? basePrice : basePrice

    // Build specs
    const specs: Record<string, string> = {}
    for (const key of cat.specKeys) {
      const vals = cat.specValues[key]
      if (vals) specs[key] = vals[(globalSeed + cat.specKeys.indexOf(key)) % vals.length]
    }

    // 3 images per product
    const imgSeed1 = globalSeed + 1000
    const imgSeed2 = globalSeed + 2000
    const imgSeed3 = globalSeed + 3000

    const tags = [...cat.tags, brand.toLowerCase(), noun.toLowerCase(), adj.toLowerCase()]

    const sku = `WSP-${(catIndex + 1).toString().padStart(2, '0')}-${(i + 1).toString().padStart(4, '0')}`

    products.push({
      id: `cat${catIndex}-prod${i}`,
      sku,
      name,
      brand,
      category: cat.name,
      subcategory: cat.subcategory,
      price,
      originalPrice,
      discount: disc,
      images: [img(imgSeed1), img(imgSeed2), img(imgSeed3)],
      description: `${name} by ${brand}. ${
        cat.name === 'Books'
          ? 'An essential read for anyone passionate about ' +
            noun.toLowerCase() +
            '. Expertly crafted with engaging prose and actionable insights that keep you turning the page.'
          : `A premium ${noun.toLowerCase()} from ${brand}'s flagship ${cat.name} collection. Designed for everyday versatility and lasting quality, crafted with premium materials and expert craftsmanship.`
      }`,
      rating: rating(globalSeed),
      reviews: reviews(globalSeed),
      inStock: inStock(globalSeed),
      stock: stock(globalSeed),
      badge: badge(globalSeed, price, originalPrice),
      tags: [...new Set(tags)],
      specs,
      colors: cat.colors,
      sizes: cat.sizes,
    })
  }
  return products
}

// ── Export full catalog ───────────────────────────────────────────────────────
export const CATALOG: CatalogProduct[] = CATEGORIES.flatMap((cat, i) => makeProducts(cat, i))

export const CATALOG_CATEGORIES = CATEGORIES.map((c) => c.name)

export const CATALOG_CATEGORY_MAP = Object.fromEntries(
  CATEGORIES.map((c, i) => [c.name, CATALOG.slice(i * 100, (i + 1) * 100)]),
)

export function getCatalogProduct(id: string): CatalogProduct | undefined {
  return CATALOG.find((p) => p.id === id)
}

export function searchCatalog(query: string, limit = 50): CatalogProduct[] {
  const q = query.toLowerCase()
  return CATALOG.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q)),
  ).slice(0, limit)
}
